Updated css
2006-cpu/code-brigade pull request #162
Opened 2020-12-05 08:08 UTC by laurencereeds

2020-12-05 20:34 UTC, tillyninjaspace requested changes
Can you fix the child key prop issues in red that show in the console?

2020-12-05 21:17 UTC, tillyninjaspace reviewed
See my comments regarding taking out { product && 
for rendering. Does it show any errors on your side at any point?

2020-12-05 21:17 UTC, tillyninjaspace commented on src/components/Product.js
> -            {
A bit worried about leaving this conditional out, will it cause a render issue? What are your thoughts, @zachgarrett24 ?

2020-12-06 02:58 UTC, tillyninjaspace approved these changes
Thanks for clarifying on the { product && for the product.js file

2020-12-06 03:04 UTC, zachgarrett24 approved these changes
looks good

2020-12-06 03:04 UTC, merged